# Generated by Django 4.1 on 2022-08-22 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('availability_starts', models.TimeField(default=datetime.time(9, 0))),
                ('availability_ends', models.TimeField(default=datetime.time(17, 0))),
                ('availability_mask', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('starts', models.TimeField()),
                ('ends', models.TimeField()),
                ('mask', models.BigIntegerField()),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.user')),
            ],
        ),
    ]
